import { MusicalEra } from './musical-era';
import { MusicalGenre } from './musical-genre';
import { MusicalInstrument } from './musical-instrument';
import { MusicalKey } from '../work/musical-key';

/**
 * 時代 (MusicalEra) のラベル定義
 */
export const MUSICAL_ERA_LABELS: Record<MusicalEra, string> = {
  [MusicalEra.MEDIEVAL]: '中世 (Medieval)',
  [MusicalEra.RENAISSANCE]: 'ルネサンス (Renaissance)',
  [MusicalEra.BAROQUE]: 'バロック (Baroque)',
  [MusicalEra.CLASSICAL]: '古典派 (Classical)',
  [MusicalEra.EARLY_ROMANTIC]: '前期ロマン派 (Early Romantic)',
  [MusicalEra.MID_ROMANTIC]: '中期ロマン派 (Mid Romantic)',
  [MusicalEra.LATE_ROMANTIC]: '後期ロマン派 (Late Romantic)',
  [MusicalEra.IMPRESSIONISM]: '印象主義 (Impressionism)',
  [MusicalEra.MODERN]: '近代 (Modern)',
  [MusicalEra.CONTEMPORARY]: '現代 (Contemporary)',
};

/**
 * 調性 (MusicalKey) のラベル定義
 */
export const MUSICAL_KEY_LABELS: Record<MusicalKey, string> = {
  // Major
  [MusicalKey.C_MAJOR]: 'ハ長調 (C Major)',
  [MusicalKey.C_SHARP_MAJOR]: '嬰ハ長調 (C# Major)',
  [MusicalKey.D_FLAT_MAJOR]: '変ニ長調 (Db Major)',
  [MusicalKey.D_MAJOR]: 'ニ長調 (D Major)',
  [MusicalKey.E_FLAT_MAJOR]: '変ホ長調 (Eb Major)',
  [MusicalKey.E_MAJOR]: 'ホ長調 (E Major)',
  [MusicalKey.F_MAJOR]: 'ヘ長調 (F Major)',
  [MusicalKey.F_SHARP_MAJOR]: '嬰ヘ長調 (F# Major)',
  [MusicalKey.G_FLAT_MAJOR]: '変ト長調 (Gb Major)',
  [MusicalKey.G_MAJOR]: 'ト長調 (G Major)',
  [MusicalKey.A_FLAT_MAJOR]: '変イ長調 (Ab Major)',
  [MusicalKey.A_MAJOR]: 'イ長調 (A Major)',
  [MusicalKey.B_FLAT_MAJOR]: '変ロ長調 (Bb Major)',
  [MusicalKey.B_MAJOR]: 'ロ長調 (B Major)',
  [MusicalKey.C_FLAT_MAJOR]: '変ハ長調 (Cb Major)',

  // Minor
  [MusicalKey.C_MINOR]: 'ハ短調 (C Minor)',
  [MusicalKey.C_SHARP_MINOR]: '嬰ハ短調 (C# Minor)',
  [MusicalKey.D_MINOR]: 'ニ短調 (D Minor)',
  [MusicalKey.D_SHARP_MINOR]: '嬰ニ短調 (D# Minor)',
  [MusicalKey.E_FLAT_MINOR]: '変ホ短調 (Eb Minor)',
  [MusicalKey.E_MINOR]: 'ホ短調 (E Minor)',
  [MusicalKey.F_MINOR]: 'ヘ短調 (F Minor)',
  [MusicalKey.F_SHARP_MINOR]: '嬰ヘ短調 (F# Minor)',
  [MusicalKey.G_MINOR]: 'ト短調 (G Minor)',
  [MusicalKey.G_SHARP_MINOR]: '嬰ト短調 (G# Minor)',
  [MusicalKey.A_MINOR]: 'イ短調 (A Minor)',
  [MusicalKey.A_SHARP_MINOR]: '嬰イ短調 (A# Minor)',
  [MusicalKey.B_FLAT_MINOR]: '変ロ短調 (Bb Minor)',
  [MusicalKey.B_MINOR]: 'ロ短調 (B Minor)',
  [MusicalKey.A_FLAT_MINOR]: '変イ短調 (Ab Minor)',

  // Plain
  [MusicalKey.C]: 'ハ調 (in C)',
  [MusicalKey.C_SHARP]: '嬰ハ調 (in C#)',
  [MusicalKey.D_FLAT]: '変ニ調 (in Db)',
  [MusicalKey.D]: 'ニ調 (in D)',
  [MusicalKey.D_SHARP]: '嬰ニ調 (in D#)',
  [MusicalKey.E_FLAT]: '変ホ調 (in Eb)',
  [MusicalKey.E]: 'ホ調 (in E)',
  [MusicalKey.F]: 'ヘ調 (in F)',
  [MusicalKey.F_SHARP]: '嬰ヘ調 (in F#)',
  [MusicalKey.G_FLAT]: '変ト調 (in Gb)',
  [MusicalKey.G]: 'ト調 (in G)',
  [MusicalKey.G_SHARP]: '嬰ト調 (in G#)',
  [MusicalKey.A_FLAT]: '変イ調 (in Ab)',
  [MusicalKey.A]: 'イ調 (in A)',
  [MusicalKey.A_SHARP]: '嬰イ調 (in A#)',
  [MusicalKey.B_FLAT]: '変ロ調 (in Bb)',
  [MusicalKey.B]: 'ロ調 (in B)',
  [MusicalKey.C_FLAT]: '変ハ調 (in Cb)',

  [MusicalKey.ATONAL]: '無調 (Atonal)',
};

/**
 * ジャンル (MusicalGenre) のラベル定義
 * ※ネストされているため、フラットなマップとして定義
 */
export const MUSICAL_GENRE_LABELS: Record<string, string> = {
  // Orchestral
  [MusicalGenre.ORCHESTRAL.SYMPHONY]: '交響曲 (Symphony)',
  [MusicalGenre.ORCHESTRAL.OVERTURE]: '序曲・前奏曲 (Overture / Prelude)',
  [MusicalGenre.ORCHESTRAL.TONE_POEM]: '交響詩 (Tone Poem)',
  [MusicalGenre.ORCHESTRAL.SUITE_ORCH]: '管弦楽組曲 (Orchestral Suite)',
  [MusicalGenre.ORCHESTRAL.SERENADE_DIVERTIMENTO]:
    'セレナード・ディヴェルティメント (Serenade / Divertimento)',
  [MusicalGenre.ORCHESTRAL.INCIDENTAL_MUSIC]: '劇付随音楽 (Incidental Music)',

  // Stage
  [MusicalGenre.STAGE.OPERA]: 'オペラ (Opera)',
  [MusicalGenre.STAGE.OPERETTA]: 'オペレッタ (Operetta)',
  [MusicalGenre.STAGE.BALLET]: 'バレエ音楽 (Ballet Music)',

  // Concerto
  [MusicalGenre.CONCERTO.PIANO_CONCERTO]: 'ピアノ協奏曲 (Piano Concerto)',
  [MusicalGenre.CONCERTO.VIOLIN_CONCERTO]: 'ヴァイオリン協奏曲 (Violin Concerto)',
  [MusicalGenre.CONCERTO.CELLO_CONCERTO]: 'チェロ協奏曲 (Cello Concerto)',
  [MusicalGenre.CONCERTO.WIND_CONCERTO]: '管楽器のための協奏曲 (Wind Concerto)',
  [MusicalGenre.CONCERTO.CONCERTO_GROSSO]: '合奏協奏曲 (Concerto Grosso)',
  [MusicalGenre.CONCERTO.CONCERTED_WORK]: '協奏的楽曲 (Concerted Work)',

  // Chamber
  [MusicalGenre.CHAMBER.CHAMBER_STRINGS]: '弦楽重奏 (String Ensemble)',
  [MusicalGenre.CHAMBER.CHAMBER_PIANO]: 'ピアノ重奏 (Piano Ensemble)',
  [MusicalGenre.CHAMBER.SONATA_DUO]: '独奏ソナタ（伴奏付） (Instrumental Sonata)',
  [MusicalGenre.CHAMBER.KEYBOARD_ENSEMBLE]: '鍵盤アンサンブル (Keyboard Ensemble)',
  [MusicalGenre.CHAMBER.CHAMBER_WIND]: '管楽アンサンブル (Wind Ensemble)',
  [MusicalGenre.CHAMBER.CHAMBER_MIXED]: '混合・その他アンサンブル (Mixed Ensemble)',

  // Solo
  [MusicalGenre.SOLO.KEYBOARD_SOLO]: '鍵盤独奏 (Keyboard Solo)',
  [MusicalGenre.SOLO.STRING_SOLO]: '弦楽器独奏 (String Solo)',
  [MusicalGenre.SOLO.WIND_SOLO]: '管楽器独奏 (Wind Solo)',
  [MusicalGenre.SOLO.SOLO_OTHER_INST]: 'その他独奏 (Other Solo)',

  // Vocal / Choral
  [MusicalGenre.VOCAL_CHORAL.LIED]: '歌曲 (Art Song / Lied)',
  [MusicalGenre.VOCAL_CHORAL.SONG_CYCLE]: '連作歌曲 (Song Cycle)',
  [MusicalGenre.VOCAL_CHORAL.MASS_REQUIEM]: 'ミサ曲・レクイエム (Mass / Requiem)',
  [MusicalGenre.VOCAL_CHORAL.ORATORIO_PASSION]: 'オラトリオ・受難曲 (Oratorio / Passion)',
  [MusicalGenre.VOCAL_CHORAL.CANTATA]: 'カンタータ (Cantata)',
  [MusicalGenre.VOCAL_CHORAL.EARLY_VOCAL]: '古楽声楽曲 (Early Vocal Music)',
  [MusicalGenre.VOCAL_CHORAL.CHORAL_OTHERS]: 'その他合唱曲 (Other Choral)',

  // Form (主要なもののみか、全部か検討。ここでは全部網羅)
  [MusicalGenre.FORM.SONATA]: 'ソナタ (Sonata)',
  [MusicalGenre.FORM.SONATA_FORM]: 'ソナタ形式 (Sonata Form)',
  [MusicalGenre.FORM.VARIATIONS]: '変奏曲 (Variations)',
  [MusicalGenre.FORM.FUGUE_COUNTERPOINT]: 'フーガ・対位法 (Fugue / Counterpoint)',
  [MusicalGenre.FORM.SUITE_PARTITA]: '組曲・パルティータ (Suite / Partita)',
  [MusicalGenre.FORM.RONDO]: 'ロンド (Rondo)',
  [MusicalGenre.FORM.TERNARY_FORM]: '三部形式 (Ternary Form)',
  [MusicalGenre.FORM.BINARY_FORM]: '二部形式 (Binary Form)',
  [MusicalGenre.FORM.CYCLIC_FORM]: '循環形式 (Cyclic Form)',
  [MusicalGenre.FORM.ARIA]: 'アリア (Aria)',
  [MusicalGenre.FORM.RECITATIVE]: 'レチタティーヴォ (Recitative)',
  [MusicalGenre.FORM.VOCAL_ENSEMBLE]: '重唱 (Vocal Ensemble)',
  [MusicalGenre.FORM.CHORUS_PIECE]: '合唱曲 (Chorus)',
  [MusicalGenre.FORM.MASS_ORDINARY]: 'ミサ通常文 (Ordinary of the Mass)',
  [MusicalGenre.FORM.REQUIEM_FORM]: 'レクイエム形式 (Requiem)',
  [MusicalGenre.FORM.PASSION_STRUCTURE]: '受難曲構造 (Passion)',
  [MusicalGenre.FORM.CHORALE]: 'コラール (Chorale)',
  [MusicalGenre.FORM.MOTET]: 'モテット (Motet)',
  [MusicalGenre.FORM.MADRIGAL]: 'マドリガル (Madrigal)',
  [MusicalGenre.FORM.LIED_SONG]: '歌曲・リート (Lied / Art Song)',
  [MusicalGenre.FORM.SONG_CYCLE_STRUCTURE]: '連作歌曲（歌曲集） (Song Cycle)',
  [MusicalGenre.FORM.STROPHIC]: '有節形式 (Strophic Form)',
  [MusicalGenre.FORM.THROUGH_COMPOSED]: '通奏形式 (Through-composed)',
  [MusicalGenre.FORM.VOCALISE]: 'ヴォカリーズ (Vocalise)',
  [MusicalGenre.FORM.PRELUDE]: '前奏曲 (Prelude)',
  [MusicalGenre.FORM.NOCTURNE]: '夜想曲 (Nocturne)',
  [MusicalGenre.FORM.IMPROMPTU]: '即興曲 (Impromptu)',
  [MusicalGenre.FORM.SCHERZO]: 'スケルツォ (Scherzo)',
  [MusicalGenre.FORM.BALLADE]: 'バラード (Ballade)',
  [MusicalGenre.FORM.FANTASIA]: '幻想曲 (Fantasia)',
  [MusicalGenre.FORM.INTERMEZZO]: '間奏曲 (Intermezzo)',
  [MusicalGenre.FORM.BAGATELLE]: 'バガテル (Bagatelle)',
  [MusicalGenre.FORM.HUMORESQUE]: 'ユモレスク (Humoresque)',
  [MusicalGenre.FORM.ROMANCE]: 'ロマンス (Romance)',
  [MusicalGenre.FORM.ARABESQUE]: 'アラベスク (Arabesque)',
  [MusicalGenre.FORM.BARCAROLLE_BERCEUSE]: '舟歌・子守歌 (Barcarolle / Berceuse)',
  [MusicalGenre.FORM.ELEGY]: '悲歌 (Elegy)',
  [MusicalGenre.FORM.ETUDE]: '練習曲 (Étude)',
  [MusicalGenre.FORM.TOCCATA]: 'トッカータ (Toccata)',
  [MusicalGenre.FORM.CAPRICE_CAPRICCIO]: '奇想曲 (Caprice / Capriccio)',
  [MusicalGenre.FORM.RHAPSODY]: '狂詩曲 (Rhapsody)',
  [MusicalGenre.FORM.TRANSCRIPTION_PARAPHRASE]: 'パラフレーズ・編曲 (Transcription)',
  [MusicalGenre.FORM.CONCERT_PIECE]: '演奏会用楽曲 (Concert Piece)',
  [MusicalGenre.FORM.CADENZA]: 'カデンツァ (Cadenza)',
  [MusicalGenre.FORM.STYLE_BRILLANT]: '華麗なる様式 (Style Brillant)',
  [MusicalGenre.FORM.ALLEMANDE]: 'アルマンド (Allemande)',
  [MusicalGenre.FORM.COURANTE]: 'クーラント (Courante)',
  [MusicalGenre.FORM.SARABANDE]: 'サラバンド (Sarabande)',
  [MusicalGenre.FORM.GIGUE]: 'ジーグ (Gigue)',
  [MusicalGenre.FORM.GAVOTTE]: 'ガヴォット (Gavotte)',
  [MusicalGenre.FORM.BOURREE]: 'ブーレ (Bourrée)',
  [MusicalGenre.FORM.PASSEPIED]: 'パスピエ (Passepied)',
  [MusicalGenre.FORM.MINUET]: 'メヌエット (Minuet)',
  [MusicalGenre.FORM.WALTZ]: 'ワルツ (Waltz)',
  [MusicalGenre.FORM.POLONAISE]: 'ポロネーズ (Polonaise)',
  [MusicalGenre.FORM.MAZURKA]: 'マズルカ (Mazurka)',
  [MusicalGenre.FORM.MARCH]: '行進曲 (March)',
  [MusicalGenre.FORM.TARANTELLA]: 'タランテラ (Tarantella)',
  [MusicalGenre.FORM.BOLERO_HABANERA]: 'ボレロ・ハバネラ (Bolero / Habanera)',
  [MusicalGenre.FORM.CZARDAS]: 'チャールダーシュ (Czardas)',
  [MusicalGenre.FORM.POLKA]: 'ポルカ (Polka)',
  [MusicalGenre.FORM.GALOP]: 'ギャロップ (Galop)',
  [MusicalGenre.FORM.PAVANE_GALLIARD]: 'パヴァーヌ・ガリアルド (Pavane / Galliard)',
  [MusicalGenre.FORM.PASSACAGLIA]: 'パッサカリア (Passacaglia)',
  [MusicalGenre.FORM.CHACONNE]: 'シャコンヌ (Chaconne)',
  [MusicalGenre.FORM.BASSO_OSTINATO]: '固執低音 (Basso Ostinato)',
  [MusicalGenre.FORM.FOLIA]: 'フォリア (Folía)',
  [MusicalGenre.FORM.SYMPHONIC_POEM_STRUCTURE]: '交響詩的構造 (Symphonic Poem)',
  [MusicalGenre.FORM.PROGRAM_SYMPHONY_FORM]: '標題交響曲形式 (Program Symphony)',
  [MusicalGenre.FORM.LEITMOTIF_SYSTEM]: 'ライトモティーフ体系 (Leitmotif)',
  [MusicalGenre.FORM.IDEE_FIXE]: '固定観念 (Idée fixe)',
  [MusicalGenre.FORM.MELODRAME]: 'メロドラマ (Mélodrame)',
  [MusicalGenre.FORM.WORD_PAINTING]: '語画法 (Word Painting)',
};

/**
 * 楽器 (MusicalInstrument) のラベル定義
 */
export const MUSICAL_INSTRUMENT_LABELS: Record<MusicalInstrument, string> = {
  // Keyboard
  [MusicalInstrument.PIANO]: 'ピアノ (Piano)',
  [MusicalInstrument.ORGAN]: 'オルガン (Organ)',
  [MusicalInstrument.HARPSICHORD]: 'チェンバロ (Harpsichord)',
  [MusicalInstrument.FORTEPIANO]: 'フォルテピアノ (Fortepiano)',
  [MusicalInstrument.CELESTA]: 'チェレスタ (Celesta)',
  [MusicalInstrument.CLAVICHORD]: 'クラヴィコード (Clavichord)',
  [MusicalInstrument.VIRGINAL]: 'バージナル (Virginal)',
  [MusicalInstrument.SPINET]: 'スピネット (Spinet)',
  [MusicalInstrument.HARMONIUM]: 'ハルモニウム (Harmonium)',
  [MusicalInstrument.GLASS_HARMONICA]: 'グラスハーモニカ (Glass Harmonica)',
  [MusicalInstrument.PORTATIVE_ORGAN]: 'ポルタティフ・オルガン (Portative Organ)',
  [MusicalInstrument.ELECTRONIC_KEYBOARD]: '電子キーボード (Electronic Keyboard)',

  // Strings
  [MusicalInstrument.VIOLIN]: 'ヴァイオリン (Violin)',
  [MusicalInstrument.VIOLA]: 'ヴィオラ (Viola)',
  [MusicalInstrument.CELLO]: 'チェロ (Cello)',
  [MusicalInstrument.DOUBLE_BASS]: 'コントラバス (Double Bass)',
  [MusicalInstrument.VIOLA_DA_GAMBA]: 'ヴィオラ・ダ・ガンバ (Viola da Gamba)',
  [MusicalInstrument.VIOLA_D_AMORE]: "ヴィオラ・ダモーレ (Viola d'Amore)",
  [MusicalInstrument.PERIOD_STRINGS]: '古楽器弦楽器 (Period Strings)',
  [MusicalInstrument.VIOLONCELLO_PICCOLO]: 'ヴィオロンチェロ・ピッコロ (Violoncello Piccolo)',
  [MusicalInstrument.VIOLONE]: 'ヴィオローネ (Violone)',
  [MusicalInstrument.VIOLINO_PICCOLO]: 'ヴィオリーノ・ピッコロ (Violino Piccolo)',
  [MusicalInstrument.BARYTON]: 'バリトン (Baryton)',
  [MusicalInstrument.ARPEGGIONE]: 'アルペジョーネ (Arpeggione)',

  // Woodwinds
  [MusicalInstrument.FLUTE]: 'フルート (Flute)',
  [MusicalInstrument.PICCOLO]: 'ピッコロ (Piccolo)',
  [MusicalInstrument.ALTO_FLUTE]: 'アルト・フルート (Alto Flute)',
  [MusicalInstrument.OBOE]: 'オーボエ (Oboe)',
  [MusicalInstrument.ENGLISH_HORN]: 'イングリッシュ・ホルン (English Horn)',
  [MusicalInstrument.CLARINET]: 'クラリネット (Clarinet)',
  [MusicalInstrument.E_FLAT_CLARINET]: '小クラリネット (Eb Clarinet)',
  [MusicalInstrument.BASS_CLARINET]: 'バスクラリネット (Bass Clarinet)',
  [MusicalInstrument.BASSOON]: 'ファゴット (Bassoon)',
  [MusicalInstrument.CONTRABASSOON]: 'コントラファゴット (Contrabassoon)',
  [MusicalInstrument.RECORDER]: 'リコーダー (Recorder)',
  [MusicalInstrument.SAXOPHONE]: 'サクソフォン (Saxophone)',
  [MusicalInstrument.TRAVERSO]: 'フラウト・トラヴェルソ (Traverso)',
  [MusicalInstrument.BASSET_HORN]: 'バセットホルン (Basset Horn)',
  [MusicalInstrument.BASSET_CLARINET]: 'バセットクラリネット (Basset Clarinet)',
  [MusicalInstrument.OBOE_D_AMORE]: "オーボエ・ダモーレ (Oboe d'Amore)",
  [MusicalInstrument.OBOE_DA_CACCIA]: 'オーボエ・ダ・カッチャ (Oboe da Caccia)',
  [MusicalInstrument.BAROQUE_OBOE]: 'バロック・オーボエ (Baroque Oboe)',
  [MusicalInstrument.HECKELPHONE]: 'ヘッケルフォーン (Heckelphone)',

  // Brass
  [MusicalInstrument.HORN]: 'ホルン (Horn)',
  [MusicalInstrument.WAGNER_TUBA]: 'ワーグナー・テューバ (Wagner Tuba)',
  [MusicalInstrument.TRUMPET]: 'トランペット (Trumpet)',
  [MusicalInstrument.CORNET]: 'コルネット (Cornet)',
  [MusicalInstrument.TROMBONE]: 'トロンボーン (Trombone)',
  [MusicalInstrument.TUBA]: 'テューバ (Tuba)',
  [MusicalInstrument.EUPHONIUM]: 'ユーフォニアム (Euphonium)',
  [MusicalInstrument.NATURAL_TRUMPET]: 'ナチュラルトランペット (Natural Trumpet)',
  [MusicalInstrument.NATURAL_HORN]: 'ナチュラルホルン (Natural Horn)',
  [MusicalInstrument.PICCOLO_TRUMPET]: 'ピッコロトランペット (Piccolo Trumpet)',
  [MusicalInstrument.FLUGELHORN]: 'フリューゲルホルン (Flugelhorn)',
  [MusicalInstrument.BASS_TROMBONE]: 'バストロンボーン (Bass Trombone)',
  [MusicalInstrument.ZINK]: 'ツィンク (Zink / Cornetto)',
  [MusicalInstrument.OPHICLEIDE]: 'オフィクレイド (Ophicleide)',

  // Voice
  [MusicalInstrument.SOPRANO]: 'ソプラノ (Soprano)',
  [MusicalInstrument.MEZZO_SOPRANO]: 'メゾ・ソプラノ (Mezzo Soprano)',
  [MusicalInstrument.ALTO]: 'アルト (Alto)',
  [MusicalInstrument.CONTRALTO]: 'コントラルト (Contralto)',
  [MusicalInstrument.COUNTERTENOR]: 'カウンターテナー (Countertenor)',
  [MusicalInstrument.TENOR]: 'テノール (Tenor)',
  [MusicalInstrument.BARITONE]: 'バリトン (Baritone)',
  [MusicalInstrument.BASS]: 'バス (Bass)',
  [MusicalInstrument.BOY_SOPRANO]: 'ボーイ・ソプラノ (Boy Soprano)',
  [MusicalInstrument.CASTRATO]: 'カストラート (Castrato)',
  [MusicalInstrument.BASS_PROFUNDO]: 'バス・プロフルンド (Bass Profundo)',
  [MusicalInstrument.CHOIR_MIXED]: '混声合唱 (Mixed Choir)',
  [MusicalInstrument.CHOIR_MALE]: '男声合唱 (Male Choir)',
  [MusicalInstrument.CHOIR_FEMALE]: '女声合唱 (Female Choir)',
  [MusicalInstrument.CHOIR_CHILDREN]: "児童合唱 (Children's Choir)",

  // Percussion
  [MusicalInstrument.TIMPANI]: 'ティンパニ (Timpani)',
  [MusicalInstrument.GLOCKENSPIEL]: 'グロッケンシュピール (Glockenspiel)',
  [MusicalInstrument.XYLOPHONE]: 'シロフォン (Xylophone)',
  [MusicalInstrument.VIBRAPHONE]: 'ヴィブラフォン (Vibraphone)',
  [MusicalInstrument.MARIMBA]: 'マリンバ (Marimba)',
  [MusicalInstrument.SNARE_DRUM]: 'スネアドラム (Snare Drum)',
  [MusicalInstrument.BASS_DRUM]: 'バスドラム (Bass Drum)',
  [MusicalInstrument.CYMBALS]: 'シンバル (Cymbals)',
  [MusicalInstrument.TRIANGLE]: 'トライアングル (Triangle)',
  [MusicalInstrument.PERCUSSION_GENERAL]: '打楽器全般 (Percussion)',
  [MusicalInstrument.TUBULAR_BELLS]: 'チューブラー・ベル (Tubular Bells)',
  [MusicalInstrument.TAM_TAM]: 'タムタム (Tam-ham)',
  [MusicalInstrument.CASTANETS]: 'カスタネット (Castanets)',
  [MusicalInstrument.TAMBOURINE]: 'タンバリン (Tambourine)',
  [MusicalInstrument.XYLORIMBA]: 'シロマリンバ (Xylorimba)',
  [MusicalInstrument.HAMMER]: 'ハンマー (Hammer)',
  [MusicalInstrument.BELLS]: 'ベル (Bells)',

  // Plucked Strings
  [MusicalInstrument.GUITAR]: 'ギター (Guitar)',
  [MusicalInstrument.LUTE]: 'リュート (Lute)',
  [MusicalInstrument.MANDOLIN]: 'マンドリン (Mandolin)',
  [MusicalInstrument.HARP]: 'ハープ (Harp)',
  [MusicalInstrument.THEORBO]: 'テオルボ (Theorbo)',
  [MusicalInstrument.BAROQUE_GUITAR]: 'バロック・ギター (Baroque Guitar)',
  [MusicalInstrument.VIHUELA]: 'ビウエラ (Vihuela)',
  [MusicalInstrument.LYRE]: 'リラ (Lyre)',
  [MusicalInstrument.ZITHER]: 'ツィター (Zither)',
  [MusicalInstrument.BALALAIKA]: 'バラライカ (Balalaika)',

  // Others
  [MusicalInstrument.BASSO_CONTINUO]: '通奏低音 (Basso Continuo)',
  [MusicalInstrument.ELECTRONICS]: '電子音響 (Electronics)',
};
